name: Scheduled data update
on:
  schedule:
    - cron:  '40 10,13,16 * * *'
jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Prepare config
      run: |
        cp config.dist.yml config.yml
    - name: Set APIKEY
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "APIKEY"
        replace: ${{ secrets.APIKEY }}
        include: "config.yml"
    - name: Run get_data.py
      run: python get_data.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*
        git commit -m "Scheduled data update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}